dataset: "cifar100"
n_classes_coarse: 20
n_classes_fine: 100
checkpath: '/data/Tian/zxj/cc/hccl/checkpoints/emb_07051103_1.pth'
classify_learning_rate: 0.001
emb_learning_rate: 0.001
temperature: 0.05